services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - '8080:8080'
